GCE-STAFF/Models/Reservation.cs
using System;
namespace Web_app_customer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Reservation
    {
        [Key]
        public int ReservationId { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public bool CheckedIn { get; set; }
        public bool CheckedOut { get; set; }
        public int RoomRoomId { get; set; }
        public string UserUsername { get; set; }

        public virtual Room Room { get; set; }
        public virtual User User { get; set; }
    }
}

GCE-STAFF/Models/Room.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Web_app_customer.Models
{
    public partial class Room
    {

        public Room()
        {
            this.Reservations = new HashSet<Reservation>();
            this.Tasks = new HashSet<Task>();
        }

        [Key]
        public int RoomId { get; set; }
        public int NumOfBeds { get; set; }
        public int Size { get; set; }


        public virtual ICollection<Reservation> Reservations { get; set; }

        public virtual ICollection<Task> Tasks { get; set; }
    }


    
}

GCE-STAFF/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace GCE_STAFF.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

GCE-STAFF/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.Logging;
using Web_app_customer;
using Web_app_customer.Models;

namespace GCE_STAFF.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        private readonly Oblig4Context _context;

        [ViewData]
        public List<Reservation> reservations { get; set; }

        [ViewData]
        public List<Room> rooms { get; set; }

        [ViewData]
        public List<Web_app_customer.Models.Task> tasks { get; set; }

        [ViewData]
        public List<User> users { get; set; }

        [ViewData]
        public String employeeType { get; set; } = "";

        [ViewData]
        public int state { get; set; } = -1;

        public IndexModel(ILogger<IndexModel> logger, Oblig4Context context)
        {
            _logger = logger;
            _context = context;

        }

        public async System.Threading.Tasks.Task OnGetAsync()
        {

            reservations = await _context.reservations.ToListAsync();
            rooms = await _context.rooms.ToListAsync();
            tasks = await _context.tasks.ToListAsync();
        }


        public async Task<ActionResult> OnPostSelectState(String personnel, String state)
        {
            reservations = await _context.reservations.ToListAsync();
            rooms = await _context.rooms.ToListAsync();
            tasks = await _context.tasks.ToListAsync();
            if (!String.IsNullOrEmpty(state))
            {

                this.state = Int32.Parse(state);

            }
            this.employeeType = personnel;

            return Page();

        }

        public async Task<ActionResult> OnPostChangeState(String viewState, String personnel, String state, String taskId)
        {
            reservations = await _context.reservations.ToListAsync();
            rooms = await _context.rooms.ToListAsync();
            tasks = await _context.tasks.ToListAsync();

            Web_app_customer.Models.Task task =  tasks.First(x => x.TaskId == Int32.Parse(taskId));
            if (!String.IsNullOrEmpty(state) && task != null)
            {

                task.State = Int32.Parse(state);
                _context.Update<Web_app_customer.Models.Task>(task);
                _context.SaveChanges();

            }

            this.state = Int32.Parse(viewState);
            this.employeeType = personnel;
            reservations = await _context.reservations.ToListAsync();
            rooms = await _context.rooms.ToListAsync();
            tasks = await _context.tasks.ToListAsync();

            return Page();

        }

        public async Task<ActionResult> OnPostChangeNote(String viewState, String personnel, String note, String taskId)
        {
            reservations = await _context.reservations.ToListAsync();
            rooms = await _context.rooms.ToListAsync();
            tasks = await _context.tasks.ToListAsync();

            Web_app_customer.Models.Task task = tasks.First(x => x.TaskId == Int32.Parse(taskId));
            if (!String.IsNullOrEmpty(note) && task != null)
            {

                task.Note = note;
                _context.Update<Web_app_customer.Models.Task>(task);
                _context.SaveChanges();

            }

            this.state = Int32.Parse(viewState);
            this.employeeType = personnel;
            reservations = await _context.reservations.ToListAsync();
            rooms = await _context.rooms.ToListAsync();
            tasks = await _context.tasks.ToListAsync();

            return Page();

        }

        public async Task<ActionResult> OnPostSelectEmployee(String state, String personnel)
        {

            reservations = await _context.reservations.ToListAsync();
            rooms = await _context.rooms.ToListAsync();
            tasks = await _context.tasks.ToListAsync();
            this.state = Int32.Parse(state);
            if (!String.IsNullOrEmpty(personnel))
            {

                employeeType = personnel;


            }

            return Page();
        }
    }
}

GCE-STAFF/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace GCE_STAFF.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

GCE-STAFF/Pages/Index.cshtml
@page
@model IndexModel
@using Web_app_customer.Models;
@{
    ViewData["Title"] = "Home page";
    String emplyoeeType = (String)ViewData["employeeType"];
    List<Reservation> students = (List<Reservation>)ViewData["reservations"];
    List<Room> rooms = (List<Room>)ViewData["rooms"];
    int state = (int)ViewData["state"];
    List<Web_app_customer.Models.Task> tasks = (List<Web_app_customer.Models.Task>)ViewData["tasks"];
}

<div class="text-center">
    <h1 class="display-4">Welcome to GCE hotell staff system</h1>
    <form asp-page-handler="selectEmployee" method="post">
        <input type="hidden" value="@state" name="state" />
        <input checked="@emplyoeeType.Equals("cleaning")" type="radio" name="personnel" value="cleaning" onclick="this.form.submit()" /> Cleaning
        <input checked="@emplyoeeType.Equals("service")" type="radio" name="personnel" value="service" onclick="this.form.submit()" /> Service
        <input checked="@emplyoeeType.Equals("maintenance")" type="radio" name="personnel" value="maintenance" onclick="this.form.submit()" /> Maintenance
    </form>

    <br />


    <br />
    @if (emplyoeeType != "")
    {
        <h4> Welcome @emplyoeeType </h4>
    }

    <br />
    <br />
    @* 0 Service
        1 Maintenance
        2 Cleaning *@
    @switch (emplyoeeType)
    {
        case "cleaning":
            <p> Status </p>
            <form asp-page-handler="SelectState" method="post">
                <input type="hidden" value="@emplyoeeType" name="personnel" />
                <select name="state" onchange="this.form.submit()">
                    <option selected="@(state==-1)" value="-1"> All </option>
                    <option selected="@(state==0)" value="0"> New </option>
                    <option selected="@(state==1)" value="1"> In progress </option>
                    <option selected="@(state==2)" value="2"> Finished </option>
                </select>
            </form>
            <br />
            <table class="table">
                <thead>

                    <tr>
                        <th> Room Number</th>
                        <th> Info</th>
                        <th> Note</th>
                        <th> Status </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var t in tasks)
                    {
                        @if (t.Type == 2 && t.Room.Reservations.All(r => r.CheckedOut) && (t.State == state || state == -1))
                        {

                            <tr>
                                <td> @t.RoomRoomId </td>
                                <td> @t.Info </td>
                                <td>
                                    <form asp-page-handler="changeNote" method="post">
                                        <input type="hidden" value="@t.TaskId" name="taskId" />
                                        <input type="hidden" value="@state" name="viewState" />
                                        <input type="hidden" value="@emplyoeeType" name="personnel" />
                                        <input type="text" name="note" value="@t.Note" />
                                        <button type="submit"> Change note </button>
                                    </form>
                                 </td>
                                <td>
                                    <form asp-page-handler="changeState" method="post">
                                        <input type="hidden" value="@t.TaskId" name="taskId" />
                                        <input type="hidden" value="@state" name="viewState" />
                                        <input type="hidden" value="@emplyoeeType" name="personnel" />
                                        <select name="state" onchange="this.form.submit()">
                                            <option selected="@(t.State==0)" value="0"> New </option>
                                            <option selected="@(t.State==1)" value="1"> In progress </option>
                                            <option selected="@(t.State==2)" value="2"> Finished </option>
                                        </select>
                                    </form>
                                </td>
                            </tr>
                        }
                    }
                </tbody>

            </table>

            break;
        case "service":
            <p> Status </p>
            <form asp-page-handler="SelectState" method="post">
                <input type="hidden" value="@emplyoeeType" name="personnel" />
                <select name="state" onchange="this.form.submit()">
                    <option selected="@(state==-1)" value="-1"> All </option>
                    <option selected="@(state==0)" value="0"> New </option>
                    <option selected="@(state==1)" value="1"> In progress </option>
                    <option selected="@(state==2)" value="2"> Finished </option>
                </select>
            </form>
            <br />
            <table class="table">
                <thead>

                    <tr>
                        <th> Room Number</th>
                        <th> Info</th>
                        <th> Note</th>
                        <th> Status </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var t in tasks)
                    {
                        @if (t.Type == 0 && (t.State == state || state == -1))
                        {

                            <tr>
                                <td> @t.RoomRoomId </td>
                                <td> @t.Info </td>
                                <td>
                                    <form asp-page-handler="changeNote" method="post">
                                        <input type="hidden" value="@t.TaskId" name="taskId" />
                                        <input type="hidden" value="@state" name="viewState" />
                                        <input type="hidden" value="@emplyoeeType" name="personnel" />
                                        <input type="text" name="note" value="@t.Note" />
                                        <button type="submit"> Change note </button>
                                    </form>
                                </td>
                                <td>
                                    <form asp-page-handler="changeState" method="post">
                                        <input type="hidden" value="@t.TaskId" name="taskId" />
                                        <input type="hidden" value="@state" name="viewState" />
                                        <input type="hidden" value="@emplyoeeType" name="personnel" />
                                        <select name="state" onchange="this.form.submit()">
                                            <option selected="@(t.State==0)" value="0"> New </option>
                                            <option selected="@(t.State==1)" value="1"> In progress </option>
                                            <option selected="@(t.State==2)" value="2"> Finished </option>
                                        </select>
                                    </form>
                                </td>
                            </tr>

                        }

                    }

                </tbody>

            </table>
            break;

        case "maintenance":
            <p> Status </p>
            <form asp-page-handler="SelectState" method="post">
                <input type="hidden" value="@emplyoeeType" name="personnel" />
                <select name="state" onchange="this.form.submit()">
                    <option selected="@(state==-1)" value="-1"> All </option>
                    <option selected="@(state==0)" value="0"> New </option>
                    <option selected="@(state==1)" value="1"> In progress </option>
                    <option selected="@(state==2)" value="2"> Finished </option>
                </select>
            </form>
            <br />
            <table class="table">
                <thead>

                    <tr>
                        <th> Room Number</th>
                        <th> Info</th>
                        <th> Note</th>
                        <th> Status </th>
                    </tr>
                </thead>
                <tbody>

                    @foreach (var t in tasks)
                    {
                        @if (t.Type == 1 && (t.State == state || state == -1))
                        {

                            <tr>
                                <td> @t.RoomRoomId </td>
                                <td> @t.Info </td>
                                <td>
                                    <form asp-page-handler="changeNote" method="post">
                                        <input type="hidden" value="@t.TaskId" name="taskId" />
                                        <input type="hidden" value="@state" name="viewState" />
                                        <input type="hidden" value="@emplyoeeType" name="personnel" />
                                        <input type="text" name="note" value="@t.Note" />
                                        <button type="submit"> Change note </button>
                                    </form>
                              
                              </td>
                                <td>
                                    <form asp-page-handler="changeState" method="post">
                                        <input type="hidden" value="@t.TaskId" name="taskId" />
                                        <input type="hidden" value="@state" name="viewState" />
                                        <input type="hidden" value="@emplyoeeType" name="personnel" />
                                        <select name="state" onchange="this.form.submit()">
                                            <option selected="@(t.State==0)" value="0"> New </option>
                                            <option selected="@(t.State==1)" value="1"> In progress </option>
                                            <option selected="@(t.State==2)" value="2"> Finished </option>
                                        </select>
                                    </form>
                                </td>
                            </tr>


                        }
                    }
                </tbody>

            </table>
            break;
        default:
            break;


    }
</div>

GCE-STAFF/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GCE_STAFF</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">GCE_STAFF</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - GCE_STAFF - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>